name: Check INTERLIS model

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
      
    - name: setup java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        java-package: 'jre'

    - name: setup ili2c
      run: |
        curl -O https://downloads.interlis.ch/ili2c/ili2c-5.3.2.zip
        unzip ili2c-5.3.2.zip ili2c.jar

    - name: check ili files
      env:
        FILES: ./ili/*.ili
      run: for f in $FILES; do java -jar ili2c.jar --modeldir %ILI_DIR;https://models.interlis.ch $f; done

